/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const HelpRequest = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'submittedAt' : IDL.Int,
  'message' : IDL.Text,
  'phone' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : IDL.Text,
  'registrationDate' : IDL.Int,
  'phoneNumber' : IDL.Text,
});
export const QRCodeData = IDL.Record({
  'url' : IDL.Text,
  'description' : IDL.Text,
  'updatedAt' : IDL.Int,
});
export const PendingRegistration = IDL.Record({
  'principal' : IDL.Principal,
  'name' : IDL.Text,
  'phoneNumber' : IDL.Text,
  'role' : IDL.Text,
  'utrNumber' : IDL.Text,
  'submittedAt' : IDL.Int,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllHelpRequests' : IDL.Func([], [IDL.Vec(HelpRequest)], ['query']),
  'getAllMembers' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getHelpRequestCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getMemberCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getMembersByRole' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
      ['query'],
    ),
  'getQRCodeData' : IDL.Func([], [IDL.Opt(QRCodeData)], ['query']),
  'getRecentHelpRequests' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(HelpRequest)],
      ['query'],
    ),
  'getStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'volunteerCount' : IDL.Nat,
          'memberCount' : IDL.Nat,
          'adminCount' : IDL.Nat,
          'totalHelpRequests' : IDL.Nat,
          'totalMembers' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isPhoneNumberRegistered' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'registerMember' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setQRCodeData' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'submitHelpRequest' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'submitPendingRegistration' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'getAllPendingRegistrations' : IDL.Func([], [IDL.Vec(PendingRegistration)], ['query']),
  'approvePendingRegistration' : IDL.Func([IDL.Text], [], []),
  'rejectPendingRegistration' : IDL.Func([IDL.Text], [], []),
  'getMyPendingRegistration' : IDL.Func([], [IDL.Opt(PendingRegistration)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const HelpRequest = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'submittedAt' : IDL.Int,
    'message' : IDL.Text,
    'phone' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : IDL.Text,
    'registrationDate' : IDL.Int,
    'phoneNumber' : IDL.Text,
  });
  const QRCodeData = IDL.Record({
    'url' : IDL.Text,
    'description' : IDL.Text,
    'updatedAt' : IDL.Int,
  });
  const PendingRegistration = IDL.Record({
    'principal' : IDL.Principal,
    'name' : IDL.Text,
    'phoneNumber' : IDL.Text,
    'role' : IDL.Text,
    'utrNumber' : IDL.Text,
    'submittedAt' : IDL.Int,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllHelpRequests' : IDL.Func([], [IDL.Vec(HelpRequest)], ['query']),
    'getAllMembers' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getHelpRequestCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getMemberCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getMembersByRole' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
        ['query'],
      ),
    'getQRCodeData' : IDL.Func([], [IDL.Opt(QRCodeData)], ['query']),
    'getRecentHelpRequests' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(HelpRequest)],
        ['query'],
      ),
    'getStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'volunteerCount' : IDL.Nat,
            'memberCount' : IDL.Nat,
            'adminCount' : IDL.Nat,
            'totalHelpRequests' : IDL.Nat,
            'totalMembers' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isPhoneNumberRegistered' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'registerMember' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setQRCodeData' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'submitHelpRequest' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'submitPendingRegistration' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
    'getAllPendingRegistrations' : IDL.Func([], [IDL.Vec(PendingRegistration)], ['query']),
    'approvePendingRegistration' : IDL.Func([IDL.Text], [], []),
    'rejectPendingRegistration' : IDL.Func([IDL.Text], [], []),
    'getMyPendingRegistration' : IDL.Func([], [IDL.Opt(PendingRegistration)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };