/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface HelpRequest {
  'id' : bigint,
  'name' : string,
  'submittedAt' : bigint,
  'message' : string,
  'phone' : string,
}
export interface QRCodeData {
  'url' : string,
  'description' : string,
  'updatedAt' : bigint,
}
export interface UserProfile {
  'name' : string,
  'role' : string,
  'registrationDate' : bigint,
  'phoneNumber' : string,
}
export interface PendingRegistration {
  'principal' : Principal,
  'name' : string,
  'phoneNumber' : string,
  'role' : string,
  'utrNumber' : string,
  'submittedAt' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllHelpRequests' : ActorMethod<[], Array<HelpRequest>>,
  'getAllMembers' : ActorMethod<[], Array<[Principal, UserProfile]>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getHelpRequestCount' : ActorMethod<[], bigint>,
  'getMemberCount' : ActorMethod<[], bigint>,
  'getMembersByRole' : ActorMethod<[string], Array<[Principal, UserProfile]>>,
  'getQRCodeData' : ActorMethod<[], [] | [QRCodeData]>,
  'getRecentHelpRequests' : ActorMethod<[bigint], Array<HelpRequest>>,
  'getStats' : ActorMethod<
    [],
    {
      'volunteerCount' : bigint,
      'memberCount' : bigint,
      'adminCount' : bigint,
      'totalHelpRequests' : bigint,
      'totalMembers' : bigint,
    }
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isPhoneNumberRegistered' : ActorMethod<[string], boolean>,
  'registerMember' : ActorMethod<[string, string, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setQRCodeData' : ActorMethod<[string, string], undefined>,
  'submitHelpRequest' : ActorMethod<[string, string, string], bigint>,
  'submitPendingRegistration' : ActorMethod<[string, string, string, string], undefined>,
  'getAllPendingRegistrations' : ActorMethod<[], Array<PendingRegistration>>,
  'approvePendingRegistration' : ActorMethod<[string], undefined>,
  'rejectPendingRegistration' : ActorMethod<[string], undefined>,
  'getMyPendingRegistration' : ActorMethod<[], [] | [PendingRegistration]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];